### ISSUE TITLE
tapis-shared: Reduce logging onf expired JWTs

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-shared-java#42]
For many months an expired JWT from 2023-06-27T02:00:11Z has been showing up as an error in the logs for several services, including systems, apps and jobs. Efforts to find the source of the request have not been successful.

To address this, the plan is to adjust how such conditions are logged.
1. If the JWT expired less than 2 months ago then log the condition as a warning without a stack trace.
2. If the JWT expired more than 2 months ago then ignore it, no log messages

Stack trace:
=========
024-08-07 16:13:06.993 ERROR [grizzly-http-server-13/] e.u.t.t.s.j.f.JWTValidateRequestFilter:538 - TAPIS_SECURITY_JWT_EXPIRED Exception message: JWT expired at 2023-06-27T02:00:11Z. Current time: 2024-08-07T16:13:06Z, a difference of 35215975993 milliseconds.  Allowed clock skew: 0 milliseconds. Claims: iss: https://dev.tapis.io/v3/tokens sub: testuser2@dev tapis/tenant_id: dev tapis/username: testuser2 tapis/account_type: user
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2023-06-27T02:00:11Z. Current time: 2024-08-07T16:13:06Z, a difference of 35215975993 milliseconds.  Allowed clock skew: 0 milliseconds.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:427)
	at edu.utexas.tacc.tapis.sharedapi.jaxrs.filters.JWTValidateRequestFilter.decodeJwt(JWTValidateRequestFilter.java:523)
	at edu.utexas.tacc.tapis.sharedapi.jaxrs.filters.JWTValidateRequestFilter.filter(JWTValidateRequestFilter.java:249)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:247)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by scblack321** [comment]
The rogue process or processes sending in expired JWTs appear to have ended.
Updated plan is to log all expired JWTs as warnings with no stack trace.
